# backend/workers/sanction.py
from fpdf import FPDF
from datetime import datetime
from pathlib import Path

def generate_sanction(customer, amount, tenure_months, rate, emi, out_dir: Path):
    out_dir.mkdir(parents=True, exist_ok=True)
    fname = f"sanction_{customer['id']}_{int(datetime.utcnow().timestamp())}.pdf"
    path = out_dir / fname
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.cell(0, 10, "Tata Capital - Demo Sanction Letter", ln=1)
    pdf.ln(4)
    pdf.cell(0, 8, f"Date: {datetime.utcnow().date().isoformat()}", ln=1)
    pdf.ln(4)
    pdf.multi_cell(0, 8, f"To,\n{customer['name']}\n\nSubject: Sanction of Personal Loan\n\nDear {customer['name']},\n\nWe are pleased to inform you that your personal loan request has been approved as below:\n")
    pdf.ln(2)
    pdf.cell(0, 8, f"Loan Amount: ₹{int(amount):,}", ln=1)
    pdf.cell(0, 8, f"Tenure: {tenure_months} months", ln=1)
    pdf.cell(0, 8, f"Rate (p.a.): {rate}%", ln=1)
    pdf.cell(0, 8, f"Monthly EMI: ₹{emi}", ln=1)
    pdf.ln(8)
    pdf.multi_cell(0, 8, "This is a demo sanction letter generated by the Techathon mock server. Please follow up with documentation and acceptance to disburse the loan.\n\nSincerely,\nTata Capital (Demo)")
    pdf.output(path)
    return path
