# backend/workers/sanction.py

"""
Sanction Agent

Responsible for generating a loan sanction letter (PDF)
after successful underwriting approval.
"""

from fpdf import FPDF
from datetime import datetime
from pathlib import Path


def generate_sanction(
    customer: dict,
    amount,
    tenure_months: int,
    rate: float,
    emi,
    out_dir: Path
) -> Path:
    """
    Generates a sanction letter PDF and stores it on disk.

    Args:
        customer: Customer details dictionary
        amount: Approved loan amount
        tenure_months: Loan tenure in months
        rate: Annual interest rate
        emi: Monthly EMI amount
        out_dir: Directory where PDF will be saved

    Returns:
        Path to the generated sanction PDF
    """
    # Ensure output directory exists
    out_dir.mkdir(parents=True, exist_ok=True)

    # Unique filename using customer ID and timestamp
    filename = (
        f"sanction_{customer['id']}_"
        f"{int(datetime.utcnow().timestamp())}.pdf"
    )
    path = out_dir / filename

    # Initialize PDF document
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)

    # Header
    pdf.cell(0, 10, "Tata Capital - Demo Sanction Letter", ln=1)
    pdf.ln(4)
    pdf.cell(0, 8, f"Date: {datetime.utcnow().date().isoformat()}", ln=1)
    pdf.ln(6)

    # Convert values to primitive types to avoid FPDF encoding issues
    loan_amount = int(amount)
    try:
        emi_value = float(emi)
        emi_display = f"{emi_value:,.2f}"
    except Exception:
        emi_display = str(emi)

    # Letter body
    pdf.multi_cell(
        0,
        8,
        (
            f"To,\n{customer['name']}\n\n"
            "Subject: Sanction of Personal Loan\n\n"
            f"Dear {customer['name']},\n\n"
            "We are pleased to inform you that your personal loan "
            "request has been approved as per the details below:\n"
        )
    )
    pdf.ln(2)

    # Loan details
    pdf.cell(0, 8, f"Loan Amount: Rs. {loan_amount:,}", ln=1)
    pdf.cell(0, 8, f"Tenure: {tenure_months} months", ln=1)
    pdf.cell(0, 8, f"Rate of Interest (p.a.): {rate}%", ln=1)
    pdf.cell(0, 8, f"Monthly EMI: Rs. {emi_display}", ln=1)
    pdf.ln(8)

    # Disclaimer
    pdf.multi_cell(
        0,
        8,
        (
            "This is a demo sanction letter generated by the "
            "Techathon mock server. Please complete documentation "
            "and acceptance formalities to proceed with disbursement.\n\n"
            "Sincerely,\n"
            "Tata Capital (Demo)"
        )
    )

    # Save PDF to disk (FPDF requires string path)
    pdf.output(str(path))

    return path
